name: C/C++ CI build parseTree

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run_tests
      run: cd test && make && ./main
    - name: static_check
      run: cd test && make static