name: C/C++ CI build parseTree

on:
  push:
    branches: ["master", "devel"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: cd test && make tests && ./test
      - name: static_check_test
        run: cd test && make static
