name: C/C++ CI build parseTree

on:
  push:
    branches: ["master", "devel"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev
      - uses: actions/checkout@v3
      - name: make test case file
        run: cd test && make gen_tests && ./gen_tests -min 5 -max 20 -N 10000 -f test/test_out.json
      - name: run tests
        run: cd test && make tests && ./test
      - name: static_check_test
        run: cd test && make static
